# Generated by Django 5.1.4 on 2026-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prime_mensuelle', models.IntegerField(verbose_name='Prime Mensuelle (FCFA)')),
                ('couverture_max', models.IntegerField(verbose_name='Couverture Maximale (FCFA)')),
                ('type_produit', models.CharField(choices=[('VIE', 'Assurance Vie'), ('DECES_INVALIDITE', 'Décès et Invalidité')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée')], default='ACTIVE', max_length=20)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insuranceproduct')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
