# Generated by Django 5.1.4 on 2026-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.IntegerField(verbose_name='Montant payé (FCFA)')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('penalites', models.IntegerField(default=0, verbose_name='Pénalités (FCFA)')),
                ('interets', models.IntegerField(default=0, verbose_name='Intérêts (FCFA)')),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.repaymentschedule')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
