# Generated by Django 5.1.4 on 2026-06-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_fix_taux_interet_default'),
        ('repayements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ['AGENT', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(verbose_name='Montant envoyé (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (MTN / Orange / Wave)'), ('ESPECES', 'Espèces en agence'), ('VIREMENT', 'Virement bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_transaction', models.CharField(blank=True, max_length=120, verbose_name='Référence / ID transaction')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('note_client', models.TextField(blank=True, verbose_name='Note du client')),
                ('note_agent', models.TextField(blank=True, verbose_name="Note de l'agent")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_validateur', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['AGENT', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Agent validateur')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='credit.repaymentschedule', verbose_name='Échéance concernée')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='repayements.payment', verbose_name='Paiement créé')),
            ],
            options={
                'verbose_name': 'Demande de paiement',
                'verbose_name_plural': 'Demandes de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
