# Generated by Django 5.1.4 on 2026-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.IntegerField(verbose_name='Montant demandé (FCFA)')),
                ('motif', models.TextField(verbose_name='Motif du prêt')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En Analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20, verbose_name='Statut')),
                ('score_eligibilite', models.FloatField(default=0.0, verbose_name="Score d'éligibilité")),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='credits/documents/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_credits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_du', models.IntegerField(verbose_name='Montant dû (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='credit.creditrequest')),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
    ]
