# Generated by Django 5.1.4 on 2026-06-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description complémentaire'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='duree_mois',
            field=models.IntegerField(default=12, verbose_name='Durée (mois)'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='taux_interet',
            field=models.FloatField(default=0.12, verbose_name="Taux d'intérêt annuel"),
        ),
    ]
