# Generated by Django 5.1.4 on 2026-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_add_duree_taux_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='taux_interet',
            field=models.FloatField(default=12.0, verbose_name="Taux d'intérêt annuel (%)"),
        ),
    ]
